CC=g++
OT=ot
TEST=test
LIBRARIES=-lpthread util/Miracl/miracl.a -lssl -lcrypto -lgmp -lgmpxx 
MIRACL_PATH= -I./util/Miracl
SOURCES_UTIL=util/*.cpp
OBJECTS_UTIL=util/*.o
SOURCES_OTMAIN=mains/otmain.cpp
OBJECTS_OTMAIN=mains/otmain.o
SOURCES_TEST=mains/test.cpp
OBJECTS_TEST=mains/test.o
SOURCES_CRYPTO=util/crypto/*.cpp
OBJECTS_CRYPTO=util/crypto/*.o
SOURCES_OT=ot/*.cpp
OBJECTS_OT=ot/*.o
OBJECTS_MIRACL= util/Miracl/*.o
COMPILER_OPTIONS=-O3# -mavx -maes  -mpclmul -DRDTSC -DTEST=AES128
DEBUG_OPTIONS=-g3 -ggdb 
BATCH=
INCLUDE=-I..

all: ${OT}

ot: ${OBJECTS_UTIL} ${OBJECTS_CRYPTO} ${OBJECTS_MIRACL} ${OBJECTS_OT} ${OBJECTS_OTMAIN}
	${CC} -o ot.exe ${CFLAGS} ${OBJECTS_OTMAIN} ${OBJECTS_UTIL} ${OBJECTS_CRYPTO} ${OBJECTS_OT} ${OBJECTS_MIRACL} ${MIRACL_PATH} ${LIBRARIES} ${COMPILER_OPTIONS} ${DEBUG_OPTIONS}
	
test: ${OBJECTS_UTIL} ${OBJECTS_CRYPTO} ${OBJECTS_MIRACL} ${OBJECTS_OT} ${OBJECTS_TEST}
	${CC} -o test.exe ${CFLAGS} ${OBJECTS_TEST} ${OBJECTS_UTIL} ${OBJECTS_CRYPTO} ${OBJECTS_OT} ${OBJECTS_MIRACL} ${MIRACL_PATH} ${LIBRARIES} ${COMPILER_OPTIONS} ${DEBUG_OPTIONS}
	
${OBJECTS_OTMAIN}: ${SOURCES_OTMAIN}$
	@cd mains; ${CC} -c ${INCLUDE} ${CFLAGS} ${COMPILER_OPTIONS} ${DEBUG_OPTIONS} otmain.cpp 

${OBJECTS_UTIL}: ${SOURCES_UTIL}$  
	@cd util; ${CC} -c ${INCLUDE} ${CFLAGS} ${BATCH} ${COMPILER_OPTIONS} ${DEBUG_OPTIONS} *.cpp

${OBJECTS_OT}: ${SOURCES_OT}$
	@cd ot; ${CC} -c ${INCLUDE} ${CFLAGS} ${BATCH} ${COMPILER_OPTIONS} ${DEBUG_OPTIONS} *.cpp 

${OBJECTS_CRYPTO}: ${SOURCES_CRYPTO}$
	@cd util/crypto; ${CC} -c ${INCLUDE} ${CFLAGS} ${BATCH} ${COMPILER_OPTIONS} ${DEBUG_OPTIONS} *.cpp 

clean:
	rm -rf ot.exe test.exe ${OBJECTS_UTIL} ${OBJECTS_OTMAIN} ${OBJECTS_OT} ${OBJECTS_CRYPTO} ${OBJECTS_TEST}

