cmake_minimum_required(VERSION 3.13)

find_package(Relic QUIET)
if(Relic_FOUND OR TARGET Relic::relic)
    message(STATUS "Found Relic.")
elseif(NOT Relic_FOUND AND NOT TARGET Relic::relic)
    if("${Relic_SOURCE}" STREQUAL "")
        file(GLOB Relic_FILE_LIST "${PROJECT_SOURCE_DIR}/extern/Relic/*")
        list(LENGTH Relic_FILE_LIST Relic_NUM_FILES)
        #if Relic directory is empty
        if(Relic_NUM_FILES EQUAL 0)
            message(STATUS "Relic was not found. Fetching Relic...")
        else()
            message(STATUS "Relic was found in: ${PROJECT_SOURCE_DIR}/extern/Relic")
            set(Relic_SOURCE "${PROJECT_SOURCE_DIR}/extern/Relic")
        endif()
    endif()
    include(FetchRelic)
    if(ANDROID AND Relic_LIBRARY_TYPE STREQUAL "SHARED")
        set(CMAKE_SHARED_LINKER_FLAGS ${TMP})
    endif()
    include(ExternalBuildHelper)
    install_imported_library(Relic::relic "Relic")
endif()
